#!/usr/bin/env ruby
# one argument : line of text
# one return code : zero for accepted message
require 'net/http';
require 'uri';
require 'cgi';
#1: Simple POST
tmp_name = '.last-screen-palv.png'
`scrot #{tmp_name}`
file_data = File.new(tmp_name,'rb');
#`rm {tmp_name}`
case res = Net::HTTP.post_form(URI.parse('http://www.tumblr.com/api/write'),
{
'email'=>'123@robotarmyma.de', 'password'=>'oliver',
 'group' => 'adminlog.tumblr.com',
'generator' =>'palv - 0.01 ' ,
'format' => 'html',
'tags' => 'pal oneliners', 
'type' => 'photo',
'caption' => "pal:<sub>#{`whoami`.chop}@#{`hostname`}</sub>:<p>#{CGI.escapeHTML(ARGV.join(' '))}</p>",
'data' => file_data.readlines(nil),#read without seperation
})
when Net::HTTPSuccess
# OK
exit(0)
else
res.error!
exit(1)
end



=begin

    *  email - Your account's email address.
    * password - Your account's password.
    * type - The post type.
    * (content parameters) - These vary by post type.
    * generator (optional) - A short description of the application making the request for tracking and statistics, such as "John's Widget 1.0". Must be 64 or fewer characters.
    * date (optional) - The post date, if different from now, in the tumblelog's timezone. Most unambiguous formats are accepted, such as '2007-12-01 14:50:02'. Dates may not be in the future.
    * private (optional) - 1 or 0. Whether the post is private. Private posts only appear in the Dashboard or with authenticated links, and do not appear on the tumblelog's main page.
    * tags (optional) - Comma-separated list of post tags. You may optionally enclose tags in double-quotes.
    * format (optional) - html or markdown.
    * group (optional) - Post this to a group instead of your tumblelog. Value types:
         1. Domain, e.g. mygroup.tumblr.com (for public groups only)
         2. Group ID number, e.g. 1495028. Found with the Dashboard URL for that group, e.g. www.tumblr.com/group/1495028.

Post types

These are the valid values for the type parameter, with the associated content parameters that each type supports:

    * regular - Requires at least one:
          o title
          o body (HTML allowed)
    * photo - Requires either source or data, but not both. If both are specified, source is used.
          o source - The URL of the photo to copy. This must be a web-accessible URL, not a local file or intranet location.
          o data - An image file. See File uploads below.
          o caption (optional, HTML allowed)
          o click-through-url (optional)
    * quote
          o quote
          o source (optional, HTML allowed)
    * link
          o name (optional)
          o url
          o description (optional, HTML allowed)
    * conversation
          o title (optional)
          o conversation
    * video - Requires either embed or data, but not both.
          o embed - Either the complete HTML code to embed the video, or the URL of a YouTube video page.
          o data - A video file for a Vimeo upload. See File uploads below.
          o title (optional) - Only applies to Vimeo uploads.
          o caption (optional, HTML allowed)
    * audio
          o data - An audio file. Must be MP3 or AIFF format. See File uploads below.
          o caption (optional, HTML allowed)

File uploads

File uploads can be done in a data parameter where specified above. You may use either of the common encoding methods:

    * multipart/form-data method, like a file upload box in a web form. Maximum size:
          o 50 MB for videos
          o 10 MB for photos
          o 10 MB for audio
      This is recommended since there's much less overhead.
    * Normal POST method, in which the file's entire binary contents are URL-encoded like any other POST variable. Maximum size:
          o 5 MB for videos
          o 5 MB for photos
          o 5 MB for audio

Return values

We return standard HTTP status codes for each request, plus a plaintext response.

    * 201 Created - Success! The newly created post's ID is returned.
    * 403 Forbidden - Your email address or password were incorrect.
    * 400 Bad Request - There was at least one error while trying to save your post. Errors are sent in plain text, one per line.

=end

